## DataFrames

In [4]:
# DataFrames contains mutiple columns and rows
# Creating DataFrames

import pandas as pd
data = {"Name" : ["Rakshitha","Rajesh","Ramya","Bhavya"],
       "Salary" : [65000,45000,68000,53000],
       "Department" : ["IT","SALES","IT","HR"]}
df = pd.DataFrame(data)
df

        Name  Salary Department
0  Rakshitha   65000         IT
1     Rajesh   45000      SALES
2      Ramya   68000         IT
3     Bhavya   53000         HR

In [9]:
# To obtain Top n and Bottom n values
print(df.head(1))
print("\n")
print(df.tail(1))

        Name  Salary Department
0  Rakshitha   65000         IT


     Name  Salary Department
3  Bhavya   53000         HR

In [11]:
# Sort the values based on salary column from dataframe
df["Salary"].sort_values(ascending = True)

1    45000
3    53000
0    65000
2    68000
Name: Salary, dtype: int64

In [15]:
## Sort salary column in descending order
df["Salary"].sort_values(ascending = False)

2    68000
0    65000
3    53000
1    45000
Name: Salary, dtype: int64

In [16]:
# To obtain Informations about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      object
 1   Salary      4 non-null      int64
 2   Department  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [17]:
# To Obtain statistical values of SALARY column in dataset
df.describe()

             Salary
count      4.000000
mean   57750.000000
std    10688.779163
min    45000.000000
25%    51000.000000
50%    59000.000000
75%    65750.000000
max    68000.000000

In [25]:
# Let us consider an example :
# An additional column called BONUS SALARY has to be added to the dataset : Bonus is of 5000

df["Bonus Salary"] = df["Salary"]+5000

# Lets create another column that specifies the Age of Employees

df["Age"]=[23,26,43,56]

# Read the data
df

        Name  Salary Department  Bonus Salary  Age
0  Rakshitha   65000         IT         70000   23
1     Rajesh   45000      SALES         50000   26
2      Ramya   68000         IT         73000   43
3     Bhavya   53000         HR         58000   56

In [26]:
# To rename any Columns : Lets Drop age column
df.drop("Age",axis = 1, inplace = True)

# INPLACE is used to permanently delete columns from dataset 

# Read the data
df

        Name  Salary Department  Bonus Salary
0  Rakshitha   65000         IT         70000
1     Rajesh   45000      SALES         50000
2      Ramya   68000         IT         73000
3     Bhavya   53000         HR         58000

In [28]:
# To rename any column name : let us consider Bonus Salary has to converted into B_salary

df.rename(columns = {"Bonus Salary": "B_salary"},inplace =  True)

df

        Name  Salary Department  B_salary
0  Rakshitha   65000         IT     70000
1     Rajesh   45000      SALES     50000
2      Ramya   68000         IT     73000
3     Bhavya   53000         HR     58000

In [32]:
# To read Data from excel file or CSV file

# To read EXCEL FILE:
# d = pd.read_excel("path")

# To read CSV FILE:
# Path of the csv file should contain backward slash or r before "" double quote) 
d = pd.read_csv(r"C:\Users\91702\Downloads\blinkit_data.csv")
df = pd.DataFrame(d)
df

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,Regular,FDR28,Frozen Foods,2010,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,Regular,FDL50,Canned,2000,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,low fat,NCT53,Health and Hygiene,1998,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,NaN,164.5526,4.0
8519,low fat,FDN09,Snack Foods,1998,OUT027,Tier 3,Medium,Supermarket Type3,0.034706,NaN,241.6828,4.0
8520,low fat,DRE13,Soft Drinks,1998,OUT027,Tier 3,Medium,Supermarket Type3,0.027571,NaN,86.6198,4.0
8521,reg,FDT50,Dairy,1998,OUT027,Tier 3,Medium,Supermarket Type3,0.107715,NaN,97.8752,4.0
8522,reg,FDM58,Snack Foods,1998,OUT027,Tier 3,Medium,Supermarket Type3,0.000000,NaN,112.2544,4.0

In [55]:
# To See unique values in Specific columns 
df["Item Fat Content"].unique()

array(['Regular', 'Low Fat', 'low fat', 'LF', 'reg'], dtype=object)

In [69]:
# In above unique elments LF AND REG has to be replaced with "Low Fate" and "Reqular"
df.replace(["low fat","LF","reg"],["Low Fat","Low Fat","Regular"],inplace = True)
df["Item Fat Content"].unique()

array(['Regular', 'Low Fat'], dtype=object)

In [72]:
# To obtain sum of sales of SALES column
total_sales= df["Sales"].sum()

# To specify it in proper thousands formate and zero decimal value
print(f"Total Sales : {total_sales:,.0f}")

Total Sales : 1,201,681

In [48]:
# Consider another CSV file
a= pd.read_csv(r"C:\Users\91702\Downloads\netflix.csv")
a.info()

# The Release Date is in Objective Data type it has to be converted into Date datatime datatype 

a["Release_Date"] = pd.to_datetime(a["Release_Date"],errors = "coerce")
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9837 non-null   object
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   object
 5   Vote_Average       9827 non-null   object
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: float64(1), object(8)
memory usage: 691.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   datetime64[ns]
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   object
 5   Vote_Average       9827 non-null   object
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 691.8+ KB

In [53]:
# Also Vote_count has to be integer Data type

a["Vote_Count"] = pd.to_numeric(a["Vote_Count"],errors = "coerce")
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   datetime64[ns]
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9826 non-null   float64
 5   Vote_Average       9827 non-null   object
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 691.8+ KB